project:
  type: website
  output-dir: docs
  render:
   - index.qmd
   - Teacher_Guidelines.qmd
   - Content/**
   - Tutorials/**
   - "!Documentation/**"

website:
  title: "MSDA"
  navbar:
    background: "#003366"
    left:
      - text: "Course Overview"
        href: index.qmd
        
      - text: "Maths Content"
        menu:
          - text: "Week 01 – Functions"
            href: Content/Maths/lecture-01-functions.qmd
          - text: "Week 02 – exp(x) and log(x)"
            href: Content/Maths/lecture-02-exp-n-log.qmd
          - text: "Week 03 – Sequences"
            href: Content/Maths/lecture-03-sequences.qmd
          - text: "Week 04 – Differentiation"
            href: Content/Maths/lecture-04-differentiation.qmd
          - text: "Week 05 – Integration"
            href: Content/Maths/lecture-05-integration.qmd
          - text: "Week 06 – Probability"
            href: Content/Maths/lecture-06-probability.qmd
            
            
      - text: "Maths Tutorials"
        menu:
          - text: "Week 01 – Tutorial: Functions"
            href: Tutorials/Maths/workshop-01-functions.qmd
          - text: "Week 02 – Tutorial: exp(x) and log(x)"
            href: Tutorials/Maths/workshop-02-exp-n-log.qmd
          - text: "Week 03 – Tutorial: Sequences"
            href: Tutorials/Maths/workshop-03-sequences.qmd
          - text: "Week 04 – Tutorial: Differentiation"
            href: Tutorials/Maths/workshop-04-differentiation.qmd
          - text: "Week 05 – Tutorial: Integration"
            href: Tutorials/Maths/workshop-05-integration.qmd
          - text: "Week 06 – Tutorial: Probability"
            href: Tutorials/Maths/workshop-06-probability.qmd
            
            
      - text: "Stats Content"
        menu:
          - text: "Week 07 – Getting Ready with R and RStudio"
            href: Content/Stats/getting_ready_with_R_RStudio_IFP.qmd
          - text: "Week 08 – Research Questions, Variables, and Study Design"
            href: Content/Stats/week-08-content-stats.qmd
          - text: "Week 09 –Categorical variables "
            href: Content/Stats/week-09-content-stats.qmd   # note 09 vs 9 if needed
          - text: "Plots – Grammar of Graphics"
            href: Content/Stats/Plots_and_grammar.qmd
          - text: "Week 10 – "
            href: Content/Stats/week-10-content-stats.qmd
          - text: "Week 11 – "
            href: Content/Stats/week-11-content-stats.qmd
          - text: "Week 12 – "
            href: Content/Stats/week-12-content-stats.qmd
          - text: "Week 13 – "
            href: Content/Stats/week-13-content-stats.qmd
            
         
      - text: "Stats Tutorials"
        menu:
          - text: "Week 07 – Tutorial 00"
            href: Tutorials/Stats/week-7/week-07-tutorial-stats.qmd
          - text: "Week 08 – Tutorial 01"
            href: Tutorials/Stats/week-8/week-08-tutorial-stats.qmd
          - text: "Week 09 – Tutorial 02"
            href: Tutorials/Stats/week-9/week-09-tutorial-stats.qmd
          - text: "Week 10 – Tutorial 03"
            href: Tutorials/Stats/week-10/week-10-tutorial-stats.qmd
          - text: "Week 11 – Tutorial 04"
            href: Tutorials/Stats/week-11/week-11-tutorial-stats.qmd
          - text: "Week 12 – Tutorial 05"
            href: Tutorials/Stats/week-12/week-12-tutorial-stats.qmd
          - text: "Week 13 – Tutorial 06"
            href: Tutorials/Stats/week-13/week-13-tutorial-stats.qmd
          - text: "Week 14 – Tutorial 07"
            href: Tutorials/Stats/week-14/week-14-tutorial-stats.qmd
          - text: "Week 15 – Tutorial 08"
            href: Tutorials/Stats/week-15/week-15-tutorial-stats.qmd
          - text: "Week 16 – Tutorial 09"
            href: Tutorials/Stats/week-16/week-16-tutorial-stats.qmd

         
      - text: "R Support"
        menu:
          - text: "Getting Ready with R and RStudio – IFP"
            href: "R Support/getting_ready_with_R_RStudio_IFP.qmd"
          - text: "R Basics: Syntax and Variables"
            href: "R Support/R Basics_Syntax_&_Variables.qmd"


format:
  html:
    theme:
      light: default      # or another light theme if you prefer
      dark: darkly        # a built-in dark theme
      
execute:
  fig-dev: ragg_png

